---
title: Følner sequence
terms:
  - term: Følner
    macro: Folner
    prefixes:
    - prefix: "right-"
      id: def-rightFolner
    - prefix: "left-"
      id: def-leftFolner
    id: def-Folner
    translate: false
    associatedMacros:
    - command: Folner
      macro: '{\\Phi}_{#1}'
      variables: 1
      variablesDefault: '\\vphantom{}'
macros:
  - command: Density
    macro: '{d}_{#1}'
    variables: 1
    variablesDefault: '\\Folner'
author: Kai Prince SFHEA
date: last-modified
---

# Introduction

Recall the definition of a group:

::: {#def-group-recall}
## {{< term-title ref="def-group" removeURLs=true >}}

{{< term ref="def-group" block=true >}}
:::

::: {#def-rightFolner}
We define a *right-Følner sequence* in a group, $\Group$, as a sequence $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ of finite subsets of $\Gamma$ satisfying $$\lim_{N\rightarrow\infty}\frac{|\GroupOperation{(\GroupOperation{\Folner[N]}{\Inverse{\GroupElement}})}{\Folner[N]}|}{|\Folner[N]|}=1$$for all $\GroupElement\in\Group$.
:::

::: {#def-leftFolner}
Similarly, we define a *left-Følner sequence* in a group, $\Group$, as a sequence $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ of finite subsets of $\Gamma$ satisfying $$\lim_{N\rightarrow\infty}\frac{|(\Inverse{\GroupElement}\cdot\Folner[N])\cap\Folner[N]|}{|\Folner[N]|}=1 $$for all $\GroupElement\in\Group$.
:::

::: {#def-Folner}
We call a sequence a *Følner sequence* if it is both a left and right Følner sequence.
:::

A related definition is the following:

::: {#def-Density}
We call define *density of a subset $A\subseteq\Group$ with respect to a Følner sequence, $\Folner$,* as
$$\Density(A)=\lim_{N\rightarrow\infty}\frac{|\Folner[N]\cap A|}{|\Folner[N]|},$$
if it exists.
:::

For $\N$, the *natural density*, $\Density[]$, is defined when the Følner sequence is constructed with $\Folner[N]=[1,...,N]$.

# Results

::: {#thm-Test}
## The Test Theorem

This is a Theorem.
:::

::: {.callout-tip}
This is a test tip.
:::

# More Information

You can learn more about controlling the appearance of HTML output here: <https://quarto.org/docs/output-formats/html-basics.html>

